#ifndef ProjectConfuse_h
#define ProjectConfuse_h
//confuse string at Tue Apr 30 12:53:18 CST 2019
#define HttpTools CzkKDzeZBmwXlIqY
#define httpConnect zFvIqfdELDmPGGuK
#define url RjIBUkUIhotmxaQN
#define type oLJoTZTzIxolmoCN
#define headers XDPHshApxYeAzLpR
#define uploadDic HAJFjIRwGhCVpEUG
#define callback VAcjITVJRCoFfdKF
#define resultStatus AxUtoWMKvmSOEEIM
#define resultHeaders eHnEpBEsjMNLCtwt
#define resutlData ICpTygXsyDGacWlK
#define resultError rsMkAeUiQgANXJVI
#define request ERbPtBTUsopQyEWm
#define session CtqiUHKNyEXMjSfL
#define task yFXkcxpqnPijHheW
#define data AFxgDdMMtlPHeFVF
#define response hIvICkbUGklFGShQ
#define error HwDDcyDhXeMhjGVg
#define httpResponse cFptQbaAxWNBQwoH
#define headerKey AqmiqIGZFrvRvIdO
#define headerValue crTvDKkwCdCTyrzW
#define downloadJasonDataAsDictionary GIcraBfkYzjQlceD
#define resultDic BkMOtgSLmsCuIaxD
#define errorString HTbBEPWxXmPFrWKo
#define downloadJasonDataAsArray zvlsbyXyjULYABxm
#define resultArray mwmJODjNNYnbscpm
#define downloadImage mGpzZplNUDFgeipq
#define ClosureWrapper OTKhcNRCXnPBBfqO
#define SplitViewController MYuliEMEkgNFWXYV
#define totalPageArray nhhinIjlHVuAGLSP
#define totalCateArray OZNkLLTssKZenWDI
#define counter HXmZmEdFbleJPjqy
#define naviVC zqdNqVbXpdwFUQuO
#define rootVC MaZcgvzDBAQkMipS
#define detailNavi XbdwNNiweJEknypM
#define detailVC YbcpitIhSORhoRzt
#define userInfo JFNgFZvaLMZFeyNb
#define naviVCTemp mDbOWVihlonIGGpq
#define rootVCTemp iGWXAuAKEQEafVhL
#define detailNaviTemp UZLYNmHZyXBkCwOV
#define detailVCTemp kbqFtnmtHoxkHXem
#define vc GJaeHvwWoiynBNbl
#define lang RghXdpHVOdslclGx
#define isRecommend CCjJtuKIUaHWaLJJ
#define resetData ZNbkjnBilmZGmogl
#define totalPageArrayTemp fsXCWfldPHpQssQf
#define totalCateArrayTemp eBomDMsyzYxHBFlT
#define newPageArray qkXvNkrsHTYovnlO
#define dataDic BTFbqhRcDzERWtnB
#define cateName HVFxhIZchLKQDIhB
#define cateNameTemp iyghGRGujCPscnbJ
#define dataArray hfrfvIFGITXJAKrZ
#define contentDic IwgCelOfKaPuGOiq
#define pageContentObj RUJEuyFrHEAbrLWb
#define titleName DQimgQYmZTjDRrEP
#define subName GiPfFaVeNGPIRBdL
#define id SXPjWWYfnDjEFCpL
#define editTime bmggpJACmCkdjBCd
#define imageUrl OwQUNeHCpiJwZaVb
#define tagString eqmcoCwyuaviaYPw
#define tagArray dmWwblbwGVUqjruD
#define attentionArray zsqqLjBJDefdgWsG
#define indexTemp voskAploRrlHOmhg
#define attentionObj OvUffRJuxAHjMvjm
#define index OsEbXmYworLZusgY
#define resetRootViewData PNjtlbFoBPRVgLIW
#define resetDetailViewData rjpWTvIgOvFuZpZG
#define checkLogin MTOMUmuWuzAkWnFV
#define loginVC myqxWMFLHraLPCxK
#define registerVC sZlBhbdOnPBGPRRf
#define showRecommend lcQGvFnaujlZNpvG
#define maintenanceUrl pdiqeTsBLwSkypry
#define foodArray TboGvFHTdUmYvXzx
#define overWebVC FUibUHOEdlzXSkSw
#define foodDic bmjnnuRGguVlARmZ
#define titleNameTemp LUnQSrNWQfGWpFWa
#define contentUrl IxFwitMlnccPlQFp
#define contentUrlTemp HiRXhHtchGgFIvQl
#define accObj IUQRvnKQsYruAsRz
#define RootViewController tyeFwKKdiodjJvSy
#define rootTV HSYDlUNSxbroeYZO
#define RootTableView IuUFLvPegCuPryHS
#define rtInstance pVzEHQIDMiibJGUv
#define rootViewDataArray iNxmWbxUoYdAaRHt
#define cell cbpYrwgXiYStECoX
#define spVC ngkuFNoggJVJIEXa
#define iconImageView QuOUARDvQGlpFEdO
#define iconImageWidth RNjWztNAAZOaPhWn
#define nameLabel glGziKWTWArPUwjf
#define NavigationController EdHRoqMcsSVJsIeC
#define DetailNavigationController UvFpgzIuerbbPFdh
#define ViewController EAJkNmCbZUPrbKvr
#define viewControllerTV nKYhfDEmcjIApHct
#define noneLabel cjvfYxJCwrRqerEE
#define searchController WtzQFeeSYJIMshpu
#define homeName hyXjkIAhIlhMoMoa
#define attentionName fDrDyFrQbPfpzESE
#define postName CkpNjcRTTrXSzjzX
#define commentName KXXTRIAIgYaitGGK
#define userInfoName zMJDMOpblMJGkcFT
#define noneAttentionName VDZSzhsElBsGfHyr
#define searchPlaceholderName gmyJnwSdtgKjWKrb
#define searchBarBgColor EzqbbWtlAEnkPrhX
#define searchBarTextColor EQbXVcUaKyLoedrY
#define searchBarButtonColor XMwQgDxTWWUrZtbJ
#define selectCateName iuVkHQEXHaWgTjLt
#define toolbarSelectIndex GLuJyywGDTnCMpFY
#define featuresName DhcovbyZuZNlxFKo
#define toolbarHeight CPzGTSzioAeulRJx
#define toobarWidth guscjsArMWHcYwky
#define toolItems ZIoGGsuqledXygMZ
#define homeBtn DcfwrFMBnkQYGedY
#define attentionBtn ZmIXyZhIWnKMUDLl
#define postBtn emPoVMGifUVzkiDo
#define commentBtn PGXtjdWgejyRYsOf
#define userInfoBtn KQMbDXJHATbIWhvI
#define showAttention CXhhUscvgQovBmuc
#define showPost BmKvKMpsrCJuloqw
#define storyBoard ysrBJfJjViENwsSK
#define nextVC SJIiqvvFZXkaaNql
#define showComment zhfvrvkFZCpktMDY
#define discussVC HwIbAMiDycIDSaYD
#define discussObj ACVMzsGFjuyYeVdV
#define repostVC OliAhrPuQTNeTRBX
#define showUserInfo KysjyjXpfAyPBYtd
#define updateCateSelect JsJjkfnSFJmQEeTE
#define spVC mdLLvLzyZfuZhKhL
#define rootVC zEegYLVdpOOlHTdp
#define updateSearchResults QjtrsjRRhTlqQeoI
#define isContains knjLttXDGYWqpZMj
#define ViewControllerTableView tggpggkJheNvTZaZ
#define vcInstance tyBdPoYglBEPYzwU
#define allDataList ktAtEmvpomwbFWrl
#define cateDataList goLceyWIENLDaApo
#define showDataList HjcBgsAFopsboaQo
#define attIndexTemp DyksNNjASqkWHsBc
#define attIndex kGcHzGgfQQLpcpvj
#define cateIndex KqTlgJpkajvDtSNN
#define ViewControllerTableViewCell QDTpsrOBCxosxVmQ
#define cellMainView yZWDlgRdjIXhQqnO
#define cateImageView eDabTwUGxBbInJJG
#define cateTitleNameLabel ENlCJAhCHAtqaogz
#define cateSubTitleNameLabel vZMYFEYtUNrPaClF
#define cateSelectBtn AIpOCQyhqXXTfvsG
#define cateAttentionBtn YtsdwybfVbSpsoGH
#define cateDetailBtn RrkCpIHyJeKqHtxu
#define mainColor ulupXVvyHinFPSZH
#define subColor QaqQMsOZtRDAJYBA
#define PostViewController TOkrgMrmWYzHNQmM
#define cateArrowImage ocTastMXoTEoDewc
#define cateView DoYOEuUabLUQRnEE
#define cateLabel cSJiifIHoxMljqsa
#define mainLabel RMwUtxKNbuTPhESw
#define subLabel KnjEBqOsPkjvOloL
#define urlLabel XbMpgyXShbDVpQij
#define tagTitleLabel oQDkbyhleqeHhVTJ
#define imageLabel VxqXRUQECwLWXehe
#define spinner gnDtljWcUFTTDaTQ
#define mainTextField ZbKJcRhBzXBUdgxh
#define subTextField MNNBEsdscCMTeDgA
#define urlTextField PXEhVKFJonXgHCdQ
#define tagLabel hqojWjLfdZlaACrT
#define tagAddBtn rfajRKJYisbvfQoK
#define postImageIndicator UFpYzUZICmxHVwUe
#define postImageView lhGZAacOsvXmreNh
#define postImageViewHeight gVgBMdOrpvxJTfOH
#define postImageBtn LvgWoVTQOpGXZAUU
#define sendIndicatorView GDsilMGdUMSUbphf
#define sendIndicator NEMHEJOFJkBSanBK
#define nextMenuId cqYwExIuxbasPcdh
#define imagePicker jhHjjLHefDHVexJF
#define imageLink ZIitgShXRPoNFkVc
#define controller YSjsCdjTtFnGkdpU
#define textField OIjIKhGwwdWdANQc
#define okAction WuFfbnSwmwdMxpyK
#define cancelAction cOJfpwkHhCARKseT
#define toolItems ChpIyPlAZbgmsCsU
#define cancelBtn MbKHauQIMxOLZFsz
#define sendBtn nrYzclKSjomeiNUl
#define newPageObj WzYBkrttAjmAVfZq
#define df LgvJASSrHJysfLnD
#define requestPhotoAuth tobWqiwOgEvoXhdK
#define photoAuthorizationStatus IghInESpJYkRNMpZ
#define authorizationStatus UyxfVpLPhYkTPLtr
#define alertController QHjAoDqSHIEGqMBU
#define pickedImage AymBuAbJYDwVdbIJ
#define SimpleSpinner wuIShgZulWtbiSIm
#define isEnable kxJJaKEsynWFwafh
#define insideOfView ruWVhJpZhUBEtBVJ
#define spinnerDefaultItemPosition rIYGeGVhODYjnIQO
#define spinnerLeftPadding FPUfqeCfcCNpIhnT
#define spinnerRightPadding qGgTEQhxMuJOtFlr
#define leftGapView ovIneMmKTvYRExmU
#define rightGapView KvysXmDeFTTuObZb
#define spinnerTextFont djVsvcRpiohvFuoo
#define spinnerTextColor tIjeqibkcLyzITov
#define spinnerTextAlignment xYtpVvppplUJaIyv
#define spinnerDropTextColor WJaCERmHqQXwHjBx
#define spinnerDropBackgroundColor gCgjyVZxkZuqbjQF
#define spinnerDropTextAlignment XpPsgkeIXqKFCVTe
#define spinnerItemPaddingTop uCBAFSFahPOvRZnB
#define spinnerItemPaddingBottom rINZhgTmiibXoaHQ
#define spinnerScrollView IqhmeAHWdObRrmnV
#define spinnerCancelBtn sIkKwkgpnrTwiyDK
#define spinnerSourceView QbdhwihXrRAOFzza
#define spinnerLabel fMUIUcXccdQxCujI
#define spinnerTitleStringArray TWoShwQvkCpaqsJS
#define spinnerCallback uKOOMyvcWJHGewoS
#define createSpinner VEmVWfrcbydVuoIw
#define insideOfView lOlscEopoDabTDuU
#define topCons MhwbdmixsXRhpJag
#define bottomCons LJVaXWsyMcqzfpdk
#define leadCons xzMWuGHLWYlgPzUi
#define trailCons zuvPkWHOQOBXQbsl
#define topConsLeftGap WMQfVBcXwBGCFnQN
#define bottomConsLeftGap airtOyadVxWFQlev
#define leadConsLeftGap FrKOIAxQJFLqLkoV
#define widthConsLeftGap NsISIUdlLkVySBUQ
#define topConsRightGap fYONTjWPbIAsUPHL
#define bottomConsRightGap zbNQmRlPQmJoWrik
#define trailConsRightGap NGWQsLXBGXtiGIja
#define widthConsRightGap mAPzIpBJChiOrLFf
#define heightConsLabel espKMowEPKanutGu
#define widthConsLabel BcGeMmvKlBWehBbU
#define centerYConsLabel JYXrkoXjkWnlPQsm
#define leadConsLabel XCvplbBmPFhrBtIl
#define trailConsLabel HYjULguIwDQTSHVB
#define heightConsLabelView urXAvBcFHCuiegFU
#define spinnerBtn kRrJcpSkbNZyrTIw
#define topConsBtn YQbTatPAlzLtkeDD
#define bottomConsBtn HVfMYNsBFCUHFayj
#define leadConsBtn OXZVwCXAXzaDMpro
#define trailConsBtn XIpXcsxsWdZJWCrp
#define removeSpinner dSUJtDVhWmTFHEji
#define spinnerScrollViewDisplay UoKvQpLtTohMTrsN
#define absFrame FOIrIVwhmikexxDz
#define outermostView crLjosniuCoghueN
#define upSpace wOcygvgpuWZLqBXf
#define downSpace KtTfsvtwEovqyXyK
#define useUp szRDCcwbTepqtkyr
#define maxWidth MEfIjVNLEuvKQoyX
#define maxHeight QWZrOZuZcMUyxcXO
#define cSize ABOGEdgODKkwmFdo
#define cWidth xAqiUaUJnvDHfbHt
#define cHeight VOoDHpbFqrtYQmZj
#define displayItemCount VJGjVcLIecLXILyU
#define topConsCancel jjtgBogPWlzTfbnA
#define bottomConsCancel umVeAsqOijfFgFFj
#define leadConsCancel GSOhiuEqjyeqFhwI
#define trailConsCancel UlnHcJeVTaUNOyvk
#define scrollContentView AtyLkYeVAbyBNCPX
#define topCons gUJWWjkcMKwAjUuo
#define centerCons KxfNBEKupRpQzWWU
#define widthCons DVCXngSPZTRrmpTW
#define heightCons JKnARanqYFtUzXXU
#define itemBtn ZmWQjJXxVtKbYjEi
#define btnHeightCons hDYFOlcJJNRbjiTa
#define btnLeftCons wVEXvurSzURdHOkA
#define btnRightCons KcgpynSTPZIgCMDV
#define btnTopCons xEnbzxSRDPAcoRHc
#define currentItemBtn fVyFqqjdOoIkIyEP
#define itemBtn2 qgARqgxyHFxTLZqh
#define btnHeightCons2 FGvMJLlYAbbYCwkP
#define btnLeftCons2 FKQcRXWEIQyetCLt
#define btnRightCons2 PqRrxmeGZWbLIDpp
#define btnTopCons2 YeHmiPtuQZkiVJUH
#define btnBottomCons xVxenIVKAEvbFmKG
#define spinnerScrollViewCancel crNhLPdtQtDnXNKz
#define spinnerScrollBtnClick EjIxtShOyHeJnknp
#define setSelection WVrOSpGgByTJqgha
#define getAbsoluteFame bgyEZfTQsPIwWzBA
#define originX DtJsvBcvbWjsbqdy
#define originY CNEnESAdtfTujzQK
#define superView BpEwlPXqhXytFtOA
#define getOutermostView tVikEDpqEEpaoeru
#define UserInfoViewController viTzwpfvBIQFRIml
#define userInfoTV BJslrkZgAQyiPzUI
#define UserInfoTableView UsKxSxSDHEzXFqId
#define vcInstance dLpEaPltCJjNPaTN
#define imagePicker qLNLlpoBafYiwvTX
#define UserInfoTableViewCell wCeYcIXtfnhYNkzm
#define userImageView bPsxfxpzqRkDorQv
#define userImageIndicator rHDeDrWhXzcMWkHz
#define userImageSelectBtn jiHgyvLayEZOWCpe
#define userNicknameTitleLabel XFTIZuQuWWHeYTro
#define userNicknameLabel TMgVQpSsFQOYTZuX
#define userNicknameBtn wRefkCzGXlmYNFor
#define userNicknameTextField VFVvguZPYkyrFFdh
#define userEmailTitleLabel SEUpncMxuqmDlrfL
#define userEmailLabel lxKWFwsfmECnygAE
#define userEmailBtn ZjuQpnEBQeDyNgsr
#define userEmailTextField cqQAclJIMsBEtVdd
#define SystemConfig NOXNLeHPKxEKpvLd
#define appCateId jykvBvsAlcCnlWdm
#define appMainColor FpZHPKgPSXSzojlG
#define appSubColor UeGHSfFeiVqHFuYZ
#define appSubTransColor PhWELGAoXjdkKGgx
#define appMaskColor PvsBMGwIvQuJQRPN
#define appLightColor pbxjFwiYjvQhdgim
#define mTitleFont lKzuCKkmKRtktiPM
#define jpushAppKey ahLhHjmaFdjzjjmQ
#define jpushChannel rAxZuOZPXqBJUqCw
#define leanCloudAppId DlcacGuxCEZJzrhp
#define leanCloudAppKey vuFedzHvqSAtHKHK
#define sendBirdAppKey VtCzXvPiyvzSxRPR
#define appSendBirdAccountChannelUrl GNqtSuFWpXOgjYRT
#define appSendBirdNewPageChannelUrl FdrpMrTXaJDEedhX
#define appSendBirdDiscussChannelUrl AAXLUzwxLVapKSfD
#define appSendBirdRepostChannelUrl YuasiLYFPIdkUYIV
#define appSendBirdLikeChannelUrl jvlkwyrImRYoWrFf
#define RepostDiscussViewController SiBNhCvFnmalWSZR
#define backgroundView jJpFGRbClBKVGklM
#define backgroundImageView RUztGXSaQvqruzvB
#define repostTV gJIJFVOWxXEKQmNG
#define sendView XbSaaeZicQztcbVk
#define sendTextField MkqsLNThyfyXljnN
#define sendBtn nwvuJECsmDHnFMiW
#define sendBirdDiscussChannelUrl wiMaZRUfumntqldJ
#define sendBirdRepostChannelUrl ItvThQkgNhpmTbeV
#define discussId GmbangjRmvOSrKDt
#define discussObject XlvepCRoVtBoARos
#define resetData UySzILmepWAtheIi
#define discussObjectTemp YXWXgXfqYWeZsSeu
#define repostObj SivroKjPCmpQPOqX
#define setParameter IzurXZnhmFuQdOGn
#define sendBirdDiscussChannelUrl xOYbUYuvCPvNJdgv
#define sendBirdRepostChannelUrl QGZUJpzwMznyIjau
#define discussId SoazfuDQfniGijGf
#define userInfo CwqUfUAToVToHWpm
#define RepostDiscussTableViewCellM pvNKunSGDpKkqzWv
#define cellBackgroundView cUYRIfwPcxWiLcXO
#define senderImageView plJRUWhzjSrHEyUn
#define senderNicknameLabel eMtQhkIsSGrOxRmh
#define accordingImageView XtbCSKYfarvpueHc
#define accordingTitleLabel AUGvOYFqkAjhKDSX
#define accordingSubTitleLabel GQbeUfbDWsKZjpZt
#define subjectLabel uTooNdYpoRVlxoEq
#define contentLabel gRbNwfhvmkoKoSPF
#define RepostDiscussTableViewCellS WZwjJMIrEMvIiKsH
#define cellBackgroundView kAKREwwqaoRxhOjn
#define senderImageView OPvDLhPUcbxTqqCb
#define senderNicknameLabel fnpBncFKPgjpfboP
#define contentLabel VtTdoKviwLkGSWTs
#define dateLabel LCgdpLjQzAQHiZzZ
#define QueryDiscussViewController pvrTaiWoxobmNbCv
#define backgroundView jdDdMXONeuTtaWXg
#define backgroundImageView qiSAJVdtiymiqKwi
#define discussTV QhNGLPraFIQkgRwv
#define sendBirdDiscussChannelUrl RVpxoqqjGfRhdVFk
#define sendBirdRepostChannelUrl LagVYTygrwIgHIcM
#define sendBirdLikeChannelUrl VEbsBnzAgFRcgOsm
#define userInfo JACiSirmYrCXYvlc
#define discussArray pFbyhcKCbQIohBaY
#define accordingClickCallback OPPMnqmZsfrvpAhL
#define repostClickCallback BpeRgBySfGsXZlLc
#define sendBirdDiscussChannelUrl pIrEdRTevTsqhoGA
#define sendBirdRepostChannelUrl HnQNqRrzqgYBtosk
#define sendBirdLikeChannelUrl kBHoMVXoSkvoIbdi
#define accordingCallback NLztjtjAQbbpNdlV
#define cellBackgroundView GxEIDwluADCIHSFV
#define senderImageView KibnxcYHIRzkigtH
#define senderNicknameLabel vWVNaHaAGSejPcSr
#define accordingImageView RzeSZRKjFCvXEcwi
#define accordingTitleLabel XXrOEUFOHyWiCChS
#define accordingSubTitleLabel eFLsMrtUPSZslVPs
#define accordingSelectBtn yMjlZwrxjydykTlM
#define subjectLabel nALgRtBvYSodIiwb
#define contentLabel zXvBIfJbalhDfaAR
#define dateLabel tbhqzYwreKNYrJtl
#define repostBtn rxMiioUXIcaVWIGk
#define likeBtn AQxKTzClYdQxlwrz
#define backgroundView iGlRiWgorJFLofpp
#define backgroundImageView FgljHmKCxpULgpPx
#define sendDiscussView JMiYgMYEyncHFvAN
#define topBarView FnhKETOpmmYReBXc
#define topBarTitleLabel deitjUtNoKbHuZXF
#define subjectTitleLabel YSDXKIjxpYTrYxRO
#define contentTitleLabel tIKcIcoTMWnyRwaq
#define subjectStrokeView EXvQMPdkyqhAEHuY
#define subjectTextField TmlASccXmEmUBpwK
#define contentStrokeView waaDGdENRnIOzMpT
#define contentTextField EpQbDtIuHaDVwKsl
#define cancelBtn XOhmAPdzRACviELu
#define sendBtn FLbdlzYYFexAiVNW
#define sendBirdDiscussChannelUrl LolOVuqYjYFOlxNa
#define accordingObject sTUKtCTdtYYkTdEH
#define sendClickCallback IKOgJGzWSVeNqijw
#define cancelClickCallback zHPRwoEsPlNeUUap
#define sendBirdDiscussChannelUrl BfTKHUTVGZfqVQiG
#define accordingObj GoRsdXhViESmuerc
#define didSendCallback HYpJVtYpKdunYyZn
#define discussObj KGVEjKfiooNBpUHr
#define cancelCallback PaSidKITrTvGzUVb
#define LoginViewController yTIeRveNuSxGmHCU
#define backgroundView INJBiJkaAMUzEFzc
#define backgroundImageView fijIXHCcvTBtHlYN
#define loginView QlIXmKlrszihpBql
#define topBarView fJhlDveDuVxoXibf
#define topBarTitleLabel jDaveFrCcDmJPHZK
#define accountTitleLabel DeMNqiInSnmNlBJc
#define passwordTitleLabel pCAwGCTZyITOKMOf
#define accountStrokeView aQKhkIdCYaIGVSds
#define accountTextField ZCGNAgBfzhvGilYY
#define passwordStrokeView fBeZktvfziIeDdsf
#define passwordTextField roludCYrHiYJwWqp
#define cancelBtn NcDkNKpylmTftGIL
#define confirmBtn hmCJiEkBkGdXQoLU
#define sendBirdAccountChannelUrl jQuaarWFYqNkEkfN
#define RegisterViewController IKpEfCAyuKafvdCx
#define backgroundView OqdMsABsDHPyCVar
#define backgroundImageView XPpGAoyUBrjWkwJX
#define registerView heGnaLPezzyrJRpY
#define topBarView nfvWoZdVjIqwhHuU
#define topBarTitleLabel RTcmcVovvwKHWvFt
#define userImageView JYZzWRdMSRBSZHfz
#define userImageBtn zGUiEbigYgUMPASf
#define nicknameTitleLabel TawcLBqqNtGsEzTf
#define emailTitleLabel ovFYkjsmDUuYKcUH
#define passwordTitleLabel NebRpLQRigjuwRSK
#define confirmTitleLabel vIGYXUSKffuqpyGU
#define nicknameStrokeView MzHtteBopVrkRyxX
#define nicknameTextField UPkdEhJGTGgwFUbJ
#define emailStrokeView kopXxqgAhkxABKJr
#define emailTextField YKGxHiqnNMyFJzMo
#define passwordStrokeView MaeCjrLHxuEIYwUE
#define passwordTextField UOAiGeqtpLoOzAdU
#define confirmStrokeView gXfPEZFWGgkebeBL
#define confirmTextField JgvQRKNwgwWTuVmW
#define cancelBtn fKSHHXxpyuXxbwWt
#define submitBtn BzGluFsGYnZDbdPn
#define submitClickCallback jsjotcgrYzbPOBnL
#define cancelClickCallback MIoIVOClMKOJySrv
#define imagePicker nFBoWehlQXgDwHwJ
#define sendBirdLoginChannelUrl YOtvSfbcnRclhDTs
#define userImageUrl EbZBWQkLZpWCVoYz
#define sendBirdLoginChannelUrl oJXtbPxRSYNsxLyt
#define sendBirdAccountChannelUrl zzzqMrRWSmDLXxBn
#define confirmClickCallback KFiPFzioWsuFHmSz
#define cancelClickCallback NuRwsPtCuNQFpKAT
#define didRegistedCallback SuMtCoAzrdrnTLKh
#define OverWebViewController ANvYggJAntAKufjp
#define titleView AQYUdGFmqiFxwbUw
#define titleLabel RPqMTuUYtZBwSFIC
#define toolsView SseHeBvVpdRZUabZ
#define backBtn nGALmCbloMFBDNkj
#define forwardBtn zoKdwaBHsotNKJXf
#define refreshBtn JAuizHipiinTuNCg
#define shareBtn lSTZquFnhcPUPqey
#define wkWebView HYYZLcfWkJYNbcAa
#define exitName JMvRALLTuEEczsua
#define backName OfCAduLvefRPCeSc
#define forwardName MAGtfJDqgmZisICL
#define refreshName vrOKTyNEajdvowNu
#define shareName JyLeOaCmYNBmKPES
#define titleBarColor ucsyqjyeAoLafoOH
#define titleTextColor MvdLIZofyFOInqCu
#define titleTextSize hnsSPIfJATvzlJvu
#define toolsBarColor iNblAWXozWrcGzHG
#define toolsBtnColor rHBgmuLiLvStLuht
#define toolsBtnTextEnableColor mPURZqmJIFnAAlUq
#define toolsBtnTextDisableColor pyCkrtXCtucbUopY
#define toolsBtnTextSize OqTJfToXkVJLfAZE
#define cancelClickCallback NeOnPouGYieawlTk
#define accordingArray XnuPsAErywWOrIkt
#define isInnerArray kXHcVbXQbmeYsqpr
#define currentUrlIndex LaaGAMbZfhtJJFWt
#define mainView igUsjtrMyXHrzNjG
#define leftView cJwQJwhfbeSORTSH
#define rightView yTsiBaBgeImUHzLn
#define topView nxNaaePkkUOqOlZp
#define bottmView gjtkRGVhYDqykkPH
#define gotoUrl drhWwtAFEaaHILuw
#define resetBtnColor vQEnNZiFCRiSTCdU
#define loadTitleUrl wdbpIGzPhkWPozbd
#define setCancelCallback HtKqddfEcBhnrLpe
#define backBtnClick ePfgBUhxCFZcyhNO
#define forwardBtnClick OfdwnofGzKnqYYsR
#define refreshBtnClick tthUiPBrwLNVgLGE
#define shareBtnClick MGOkuUzSNtZVAnCC
#define addMessageBtn jZOrLUkoKxCyjzgW
#define messageBtn KhQXLqirZXvHUjWu
#define sendDiscussVC KzkhHEbUNIHwXOiy
#define KeyboardControlExtension SQuDMzBgJjLKBLzw
#define kvcIsKeyboardShow GvDFXtAufiRwmGPz
#define kvcKeyboardHeight vhQhutbQsExBGqcI
#define kvcMainViewFrame iciVGKOIhsgeovsg
#define kvcTargetView dLLOvaXTQJRqlJCH
#define KeyboardViewController OFfiEMtSMMqXThsz
#define mainDisplacement KgGbqWaBQiBkWYDY
#define bottomInputViewFrame AXhDfRGAqQGfzlsa
#define bottomSpace bMOsmVvioTqHeJez
#define bottomInputViewFrame sCfTgkZjcRwtDGBc
#define bottomSpace COulaMDsPAaqgyxB
#define kvcGetViewOfAbsoluteFame vXdbQHuAAbXUEeiB
#define SendBirdNavigationController ivOAuxLtWdTZKuqX
#define mTitleAttributes CLHxXfFZJiCXHleU
#define UserInfoObject RTFbFoFbGoVcDaeP
#define userPassword uWYNFRHvvxAwJAGD
#define userNickname MSYTyAzHEiBEOJkC
#define userEmail fjibslwBtsJcBhcK
#define userImageUrl KrCaFEBtYYuNHXnA
#define AttentionObject uOkWRjJmzMwmVytp
#define accordingUrlArray BRSbxvZfLdyduvkl
#define NewPageObject vPPVjYxIeuwqsiGg
#define menuId wNfxkqmsummFJzVn
#define cateName JtuwPmFVDsWjdWlH
#define titleName cREEKbOQwqiqPvgK
#define subTitleName SKbeaFPNtJQXklrM
#define tagName KYWuvPTWVgtIGvRx
#define pageUrl hOJWmdUAUxYYLWcJ
#define imageUrl ncDZwfDKbHPBtmQC
#define editTime pUmFBgaYuNVLIXQp
#define isAttention FSMmmlGcllpTZgrB
#define DiscussObject sajdPlaxiQKwNeEP
#define according ilEqOEkVveIIBdwv
#define discussId YdByZyirYwKEQurW
#define subject lgDyVceiZqAMwQGt
#define content kbKQqHFewymqTGzG
#define date qVNzLMCqLkCRrQcB
#define repostArray uOoKtVLIgHjIBUgP
#define like gyKFAXVMmgVepfYT
#define DiscussAccordingObject vEeUyarLqmvJncXK
#define accordingUrl WWFexeYVyawCZyAN
#define accordingImageUrl PHDDwRWvKhMGMKmf
#define accordingTitle DHsFWtVXhTctFGsW
#define accordingSubTitle efiNjgwRXnKDIBsX
#define DiscussRepostObject oNXFHkTxZehUMVMa
#define discussId vlWBgwDvHiDCkLoB
#define DiscussLikeObject ybIBXjkRvNwWQgos
#define userInfoArray eKgRDVRNcpYzgUrh
#define discussId JVDOfKNufkOXizsV
#define sendBirdInit FFfmcDvwobRQORAz
#define sendBirdAppId KgJyKnDFAUPqQjEA
#define sendMessageTo hOyDvIvIWukPrFJT
#define sendBirdChannelUrl fJmVvRFzuUSwwEre
#define userId xHlhxLAouWfTizrw
#define messageDic yRmBcxUeraecrIXL
#define didSendCallback IgjEkJCoovjzfXRw
#define getMessagesFrom KoUzuntpSejiqhZL
#define sendBirdChannelUrl pdwPOwUPUHkbcUzg
#define numbersOfRange mpSRDUqVmenOiZJl
#define messageArray NAKFzYGuKlkZFJxt
#define pageOfNumbers BEqfQUQQYDJoLtdu
#define listQuery RbKOvhInYoGqsqIE
#define getMessagesListQueryLoop SvAFbcqJYuECATyp
#define responseArray WgXxXVelaojkwdPc
#define userMsg npVjYqmckvfGadMr
#define msg EpETOBgNoTPakeqP
#define msgData mrLjjKEzAknebAoW
#define getSendBirdUserInfo hZkIeSofRHjYVVOb
#define setSendBirdUserInfo InAvbCIGKfGhwyFn
#define sendAccountTo MEgOfqVWfoPrZGLX
#define sendBirdAccountChannelUrl efsOxUeNYaMBHIsu
#define getAccountsFrom COFaSLnDVRxqnHhy
#define sendDiscussTo wTOCOlwgJHZZdPvG
#define sendBirdDiscussChannelUrl ReHTLobSkVVfqxRA
#define discussObject udesAdabaLMyTzYl
#define didSendCallback wRSQKokNMBSuhNTp
#define getDiscussesFrom GcBeKfUEUmltroLL
#define discussArray XGYeQmVRASCsvFfN
#define sendNewPageTo ekhGDKZTlHKcSWzB
#define sendBirdNewPageChannelUrl krtbtMAKyTossFhn
#define newPageObject RsMrHiIsUJDRGANx
#define getNewPagesFrom wYCHFjBkPysrFbQB
#define newPageArray lSEktPdwszULSQkr
#define prevMessageListQuery nNeernGmmwLiBpsm
#define sendUserAttentionTo OxySEWSesLWwNAdK
#define sendBirdAttentionChannelUrl RuqGqTBkElCrmOYu
#define attentionObject yoqmvuHoNisDKHlt
#define getUserAttentionsFrom VeWpBKNQdgeQNbqs
#define attentionArray BzASOjAziaKhfweA
#define sendRepostTo pYMbAmQoTCEhEvFV
#define sendBirdRepostChannelUrl GpjIjfzWRmYjFMkE
#define repostObject SjmpmyARTwSPNVdm
#define getRepostsFrom pCKIIAdWLwjuenwu
#define repostArray ftmeGZyDbgZsJaod
#define sendLikeTo mVAcSDnwnTcDXwrr
#define sendBirdLikeChannelUrl CnpQZkvwwrGVdRtX
#define likeObject BqHkkgznlwiDITOH
#define getLikesFrom HuqZrhwqUmSLpwjI
#define likeArray ryYcTCRzwIcpcdhX
#define getOutermostView cskCBhlMbWqxjIgT
#define getViewOfAbsoluteFame IMpoiKZJVatlSzUq
#define startIndicator pPVsbFEbYJgXKHqX
#define currentVC MJNWVmDpWXZpYuIa
#define onView VYUTQhFAjndIWciT
#define stopIndicator OaLPPOEfltfGSHOq
#define indicatorView gsKgPNqxONqXNhNH
#define matchPattern RLqcslrskMRYMxDV
#define regex KGOcRiHalZKJLaRG
#define resizeImageLimited FJblFiAakmzQZGbS
#define backToViewController OSwFXtvUuciQnssh
#define backToVC baQUEldiYYPYfmea
#define getDeviceTokenFromUserDefaults JDcSizNVzhyRNHkY
#define saveDeviceTokenToUserDefaults gvYDFrUUjEQFdmIe
#define deviceToken STCXBuPTqddZZHJo
#define getCoreDataContext OeqSfEwagDebgGeA
#define entityName QepXiyDWCZjOdrtT
#define persistentContainer EFbDeDtCWDasybaE
#define coreDataExample zZtdGTvrTLAswxNR
#define uploadImageGetLink NMYYMRRSpXZmNVns
#define urlString ftemddyReSUvrWha
#define authorization tIdwIcpPkhuvldbs
#define mashapeKey josnbkhfCHPeSJPg
#define resizeImage qfwDtsyCZEphzvrg
#define imageData OOWwqDCqVdWRQGUE
#define imageBase64 wMPIqqDCPDLrcwoZ
#define parameters DSTvRxsipmZjBvZF
#define getDownArrow KaYRQamFkmKeIBif
#define isSameUrl mVqSKZMLMxTCxNdJ
#define MatrixConcatenation NjQmxlhRdaxxByNO
#define MatrixOrDouble DRYdtnoElhcuSxBl
#define horizontalConcatenate FwagVhZkHUUmWhUY
#define resData aLksNJxZpuUdZnql
#define verticalConcatenate JeupkeZdPjeRexpO
#define Matrix gLdOkESKGskNuFqo
#define AAPoint FugtRSWuNKpUEyLZ
#define translation OhTNUhpMNPgzlaFi
#define MatrixMultiplication lbVUZEpLDjjMkIzA
#define AASphereView QZrbpIjFIHozSKVg
#define MatrixCreation udqsHdGCaZxGNGwM
#define MatrixSubscripting RhcILRfZJGUxRSFh
#define sphereContentView veGbhWNHPxaqQiTu
#define sphereView rzDzWPYpJbDxZssg
#define resetSphereView OWjuNdITMIYCUbIo
#define showSphere ezkHFEHambnpqcUK
#define tags sGKwTbyeQtuZtVYp
#define displaySize zZenZlmLxejwIhBH
#define button NKjmsCALcnGGDCKK
#define overWebVC tghqYIYyGGVZVgzJ
#define accObj umvPBAXxyrPOZHPO
#define CurrencyObject kuGIYrhGCRZcPDOd
#define id updpvWGRpXYDDqfe
#define currencyName RqYeozcHpebxSNwD
#define currencySymbol fftAmUozrNuxzMxn
#define CurrencyTools OwsbeKTrNpGAQKFm
#define freeCurrencyApiUrl ccZzFZrYWUBQzbyf
#define freeCurrencyAppKey UgLNEiNQRfIKPDPd
#define CurrencyName aWNfqcBEpaIClMIE
#define en oASmlrgkzTfPNcFo
#define cn cfDSTRGahjrxkCkj
#define getCurrencyNameCn wEmqrGIbnXEgUpyb
#define getCurrencyObjectArray GdhNDiPrqythNqAK
#define currencyArray hCdeTbNAFQxCvCMR
#define currencyDic mTvVLvmalHlofqme
#define currencyKey maTprIvzecWWqpav
#define currencyName hkSGaARlkAPkMcPU
#define currencySymbol OEuEQkVfLSAJxwWX
#define currencyObj SAfKvJcaqIEplMCT
#define currencyMainView PUaJINIMaDSDtPBM
#define currencyTitleLabel CNDklRrNfDcblTpK
#define currencyFromView CNWHKhXUyZFinfYz
#define currencyDescLabel1 pZUCbcyhvZOnNrtt
#define currencyToView HWmhAfyeMARTOIVg
#define currencyDescLabel2 zxJrxRfBmEiqqFeg
#define currencyInputTextField LwJTrGRjiKtvNGjX
#define currencyStartBtn MtYDHYScdywjPLSW
#define currencyResultTitleView EVUlNKJPudflpRti
#define currencyResultTitleLabel TLnSRnjwFqBDEnIo
#define currencyResultLabelMain ITwfLpvXmgZwxjKi
#define currencyResultLabelSub DOKexbyXcNlnjOyZ
#define currencyFromSpinner gfOVgYQyFUpbJgyD
#define currencyToSpinner NDupzZhyENFgkXlW
#define currencyObjectArray zqQTSusbWQlbuyFD
#define currencyNameArray ZZPOjHQrInPOqign
#define currencyFromNameArray IdXGSWkOOBxEUnQj
#define currencyToNameArray hdsnhFqGBDwqYQMX
#define isSpinnerInit GqIAbneUwhXyGbDW
#define currencyObjArray FgdCNKmHkqaeewwx
#define valueText eqbkauYJQTExxVOL
#define valueDouble uvOiHWRIGHiLQPcs
#define fromObjIndex nwLFoSWoQFzUbnrK
#define toObjIndex ZIAqDWuXSAaqsyRK
#define fromConName wIGMndcRTainmecj
#define toConName VVRfuKpJcoHPNwnJ
#define currencyPer fKKgoNfKLLyozjZp
#define per GkHJyyqDBNJLmxDu
#define formatter hxQsDpaKlhAXjFMB
#define valueString wMMzgMnofHtltrsx
#endif
