#ifndef ProjectConfuse_h
#define ProjectConfuse_h
//confuse string at Mon Apr 22 18:32:19 CST 2019
#define HttpTools wdALDfXOgqjTAiwV
#define httpConnect bKKKfizZxqKWyZjX
#define url LRxhqjcsUyNdujsU
#define type uGEmzfVINMMcEWJa
#define headers FBYzCVfQvIMYDzLv
#define uploadDic PqSlxrxVMjmOyFIV
#define callback oHGRVoMGxCixuRVi
#define resultStatus jeYdGEqLsPGwpAil
#define resultHeaders ALQzwaOoUSMkAdnP
#define resutlData SvdwrpVfnyeDrcbQ
#define resultError yOGtcJbiRZxMKVzM
#define request AhKPOvvVWIvvUAIG
#define session JQRFCefDbgRMqUMT
#define task KaRXPWoZbHWUDpKR
#define data RYXqTojarMzpdYWc
#define response HDOmDJdybTfaSbAj
#define error YKugCBTGHvLyQDME
#define httpResponse XJLiMvzJaKeEFPcA
#define headerKey UIHqvPvsSAznazbH
#define headerValue OAtRSBdzROmjdUXd
#define downloadJasonDataAsDictionary HzgYGPdVxxoGudJI
#define resultDic qKhiVXTvqXMRHZKx
#define errorString aetZEVPLOGksPNLl
#define downloadJasonDataAsArray dvAtBatWUlPLnWQp
#define resultArray DbOmwDVKwzGJhBmB
#define downloadImage pHbuvySBXYLhGJVW
#define ClosureWrapper WlDaiEbvIgNWbBRJ
#define SplitViewController vexpnJyxVXqbVgNG
#define totalPageArray feWWXEYlrlbBAydU
#define totalCateArray pIZtXaRLWUgcXCZb
#define counter SVmyilXkoWWkVAmR
#define naviVC LqFZIzxvbbZpZNVe
#define rootVC ZFUDuLlTItoqMvtE
#define detailNavi HoxdbjMEXeBXcQOc
#define detailVC njIMJiUDtAgduDqM
#define userInfo pXxAtdIWoqmuQDHX
#define naviVCTemp bLvtRzkOtyyAQQpd
#define rootVCTemp WRcHHrJduYZtaaDs
#define detailNaviTemp HHPVtxFajtjjsPFZ
#define detailVCTemp TkeVTGWdrKFFolcf
#define vc wFPArPCEDaYMxYNT
#define lang NdnFrPKYvdPSdBOa
#define isRecommend KbxivPUbpWaeCMvA
#define resetData UjEkSVARxdfPpbdy
#define totalPageArrayTemp nyrHFdyFEmEaFlOq
#define totalCateArrayTemp GUXlWzZFNJCKrwcK
#define newPageArray BqYtAUWOpDhMBtJo
#define dataDic vXiZAkyiokXAQvuD
#define cateName hcHlESnxRVWHMbkF
#define cateNameTemp HSMAPcikNZVMAqqR
#define dataArray IBbSeeVuvTSxmFUS
#define contentDic EKXCBdEeOvPNnwWd
#define pageContentObj fTytdOjChiTBTnvS
#define titleName pWhieYzaWUBWzGOw
#define subName SVbASCRWDllmYgwi
#define id vJByMYrRVGDtplwA
#define editTime WaeJgIvhGBwRpYkj
#define imageUrl yXmAKBiyWQIcKSJK
#define tagString KZaJZJOdCmyvHCsO
#define tagArray TErUVbNgeMimXRzs
#define attentionArray OSoIgKzZvRDhOlOF
#define indexTemp rVIRWIxWFJDRhHlQ
#define attentionObj EQtgmSymVvpfCYMu
#define index acyopnycTuzWfSPK
#define resetRootViewData mpFcnJHPnMlJXZpR
#define resetDetailViewData acprVKerEKRULIpS
#define checkLogin HvrenEXEtHZqHnUs
#define loginVC ohERaJYWBHHcUAJr
#define registerVC VoSjnSfYPmufycvn
#define showRecommend hRrKNCOuiMfWgNby
#define maintenanceUrl qnFeyLKggUGEdBdK
#define foodArray hNzdMxoYMfSCtTse
#define overWebVC oOqQLGqDMxAjraUs
#define foodDic eXTHEnbCthAyqluU
#define titleNameTemp wWgjevkUUdedmBey
#define contentUrl KlfSbqWRbPYVkXUe
#define contentUrlTemp BiBQSexEKkwERKyF
#define accObj MkKBqgQqzOvbaZEO
#define RootViewController qHAhZnafzHAiwyKD
#define rootTV pPijiSBEOvqBdIIJ
#define RootTableView tobOpvyNhEJXRJrf
#define rtInstance HkVjJAsenBgoYYAZ
#define rootViewDataArray RWlkriKhYvYFFfBF
#define cell NSlkvRiQUNEewvri
#define spVC mcNHzpvHUVMXzRdg
#define iconImageView eyWcCYfMLdBczwul
#define iconImageWidth ZoKYQpGqqAqoJmJo
#define nameLabel XJqBWsBHrpJRdhDd
#define NavigationController RRaolZsTSGUirRNP
#define DetailNavigationController dxzOARmqkokRJmZF
#define ViewController SPEPbxQhggqccnsM
#define viewControllerTV IWoDyWcDLuUfDobc
#define noneLabel tRwqlGomYpuqRyLZ
#define searchController wgxmiilsCzjZCArr
#define homeName tqgGqJkIKTlAMJOO
#define attentionName zJSWUPPXRkOJAyGo
#define postName RpYADWVnvQaNgLoG
#define commentName bKUTtasoSivbJlxH
#define userInfoName XUgVnajQrEyTXbkN
#define noneAttentionName zHfNxkUdfwRoonXU
#define searchPlaceholderName YRXMjtkuNdyQRNSR
#define searchBarBgColor SGezIeSufcwlgFNU
#define searchBarTextColor pgnfrqqLprhumAAp
#define searchBarButtonColor RYeakEODEIKmjvcg
#define selectCateName QNxYJsSmrgJjkZHz
#define toolbarSelectIndex wCJIrKkvNFuBZACl
#define featuresName OvFZcDdLzfmyPQjm
#define toolbarHeight inamwfpBVrLulFFJ
#define toobarWidth VtyGHgeihbAadahP
#define toolItems SffwyAWtUpRmbUhn
#define homeBtn aANZXbMyoVKlpFgr
#define attentionBtn COilUACiVrnYCDtI
#define postBtn YEvCSXRbgcSRMivN
#define commentBtn smUsOQJCxHlvgFuV
#define userInfoBtn ackfokLOOJAGXYCw
#define showAttention BYtfCwOgkqOYNDdv
#define showPost wtRjGyFythcyNVhj
#define storyBoard VmXNOHgzEbQQflWh
#define nextVC GugUrRZHSDYDaqGy
#define showComment nHMLwtYaZeduMwBK
#define discussVC ElYDXLjShnCfHasN
#define discussObj hybwsPPBzHoydjrY
#define repostVC lhXvAkTkgkPFiLeN
#define showUserInfo NgSbMtDSJiINbpHA
#define updateCateSelect pBAEaXnPOexFMdzn
#define spVC UzgavIDYdamLabZF
#define rootVC MRAiKuNhtohswCFg
#define updateSearchResults dsBjrLfxSetudkmH
#define isContains lnPLcLwfWYpVWCvH
#define ViewControllerTableView aHoPSxKJqgWQnLfP
#define vcInstance OOwYzjIGpGiKoNdW
#define allDataList sZzxnZueXomOlhFh
#define cateDataList QNAFvILuqZPExizl
#define showDataList cqXxaHLHNxbZfQGn
#define attIndexTemp tesqpHuZnVtVAAOd
#define attIndex kSaFrhNZHdRctApy
#define cateIndex yIOvSTwtmOIGMvqI
#define ViewControllerTableViewCell nsxsuzWbWaPvTPqp
#define cellMainView zYCwIprVDoFdSgrd
#define cateImageView SAIhqDFJTyQFbhPa
#define cateTitleNameLabel kZHthJGDULxpqQkJ
#define cateSubTitleNameLabel nZYJJpYbJHAzBOFw
#define cateSelectBtn QtzpIbMmGzWrgkTk
#define cateAttentionBtn BUvBsCGjKEewXjoc
#define cateDetailBtn OPDaewTygFjgHQgh
#define mainColor KyyZkCPPHMpIVLCj
#define subColor vTKCeYDsEvuiWvzC
#define PostViewController aurHrGjYVMOnumGl
#define cateArrowImage DbzpKaimNUeSaroN
#define cateView FerdzBQqMVfJhPKb
#define cateLabel fApNowbhOLmChXPN
#define mainLabel TOpbbWSWyKccNfUf
#define subLabel UJInMVusoNhJCtUv
#define urlLabel fNSsWbvZGbxBIgrU
#define tagTitleLabel IUoTZAbijcZuZKJV
#define imageLabel srlkDmRgnyrLPKcQ
#define spinner tNrrRcOqzqMKvFdU
#define mainTextField plnyAQqGAlHHjSJe
#define subTextField oRoKZbZJrnaisgyg
#define urlTextField fmmJbJzBqNnfWOYk
#define tagLabel PvkCGtSxdKhXZnOf
#define tagAddBtn MAXMXOFMDUAYIGdM
#define postImageIndicator PDRUgzipjvJhXINK
#define postImageView INkFGaKJxArweNAd
#define postImageViewHeight wYsFEGIggSjPafBP
#define postImageBtn LTnOMPYQmXsLRRJm
#define sendIndicatorView ucDbkaJTspAfCzka
#define sendIndicator wBnUpsJHVVJEgllQ
#define nextMenuId zXJGyfoXYUaODGlo
#define imagePicker gniuizeRinkuhcXN
#define imageLink lQlBJUIDytSxqCyn
#define controller vIutUQjdWaozSfZu
#define textField kafDWRNQsIKPqlqY
#define okAction OPlUhfnnxtbAYBcU
#define cancelAction VPevBINBUQAyYobW
#define toolItems NCjhVOUDmByiMiWM
#define cancelBtn nSReJBIXaDUrXTHI
#define sendBtn tonfrTdvFHWDocmf
#define newPageObj ETFuFgOnNhhGpJha
#define df QgpPRvtQBUDOzqoS
#define requestPhotoAuth dZWjYkmRilCKMRjK
#define photoAuthorizationStatus cQYYAprJaYvMGXxR
#define authorizationStatus VNwqpPowyXeZmugO
#define alertController sqhxvDgJQtluNkgy
#define pickedImage ayadSAjqDOXvbXOi
#define SimpleSpinner obCAQYhKYyPivIQL
#define isEnable JEHVpRKGmPVJIaSg
#define insideOfView LsEzlfqWMJuPeHwm
#define spinnerDefaultItemPosition pqzAAMWnkpLAopOU
#define spinnerLeftPadding PCrxvxlUbdhSUlaq
#define spinnerRightPadding eHsjanQwPFpwNRAE
#define leftGapView jrifFChsRwTmkQIP
#define rightGapView RxhvmNLLtlLAkfWk
#define spinnerTextFont wMKnNqNsKWLpnGov
#define spinnerTextColor gdLqfgFphxHIFlSb
#define spinnerTextAlignment QZGMIwDXQbcGbHJz
#define spinnerDropTextColor CxDmQwnPcMFaSPLL
#define spinnerDropBackgroundColor OMyDDvOxHPNsPHaU
#define spinnerDropTextAlignment XlbUpkDKOTFjUQYt
#define spinnerItemPaddingTop pKbfDNRcgAYiPWDc
#define spinnerItemPaddingBottom yvABKYWFtWUIbtpz
#define spinnerScrollView TYnzQsayZrTvNDFn
#define spinnerCancelBtn fIkEounJfSzCoAcI
#define spinnerSourceView oIvMvjWGmdOHFUpz
#define spinnerLabel MrHuZkuwBXrkxcdL
#define spinnerTitleStringArray LJwuMyeoIODNOUtx
#define spinnerCallback RpDfkSNlwqVulJig
#define createSpinner vervQlzRvlnSAaAP
#define insideOfView odctfFqHGGbBzEyQ
#define topCons QTIvnnmTsPxjCzPJ
#define bottomCons OIgiuQktPxRGbXMT
#define leadCons LJSSejVugEHaotmk
#define trailCons sKMIMgPHwLmGQofq
#define topConsLeftGap FdvxYHfAftUXrrAh
#define bottomConsLeftGap NFUUhSLRpgnDKFxX
#define leadConsLeftGap YyiyUvgnPDTCzOmH
#define widthConsLeftGap TCHYqqdJxsRdfTBr
#define topConsRightGap daUsJOlyNhmdhUgW
#define bottomConsRightGap KVXSYQYlCvmScqmO
#define trailConsRightGap fSjpWJoecUUDbRrY
#define widthConsRightGap OekdeoNAUaApLnUF
#define heightConsLabel YVoGuQUiofiDKrou
#define widthConsLabel hbwmVyRQAvuQHCUF
#define centerYConsLabel pTWiQKiBwbZaqdqE
#define leadConsLabel sMfkHxNOJaNATzXv
#define trailConsLabel JRZBQxXjsiDKzEMw
#define heightConsLabelView BlXCRCednWmSPapw
#define spinnerBtn IXUxohWEBXpECbdw
#define topConsBtn VYYXGEoCfEvetalc
#define bottomConsBtn JZzGNxslREDzdJei
#define leadConsBtn xARYdyPwNmpCuyoP
#define trailConsBtn kXlAIdUaeLjtmapG
#define removeSpinner JCyNpVIEEnzVpXKE
#define spinnerScrollViewDisplay aSkKCsyYJacGSOBR
#define absFrame wqZMGZCJCNIiyKQX
#define outermostView hppvWTSOuDSXkFKy
#define upSpace oncaBMRYCUostZgN
#define downSpace QnBWstABRYqxjoIO
#define useUp WnQszMOomEOXmTJL
#define maxWidth rkUwhNGyhZGtmgyT
#define maxHeight tqesAArZYzUROrAV
#define cSize AocMnBaBFiEwDCkC
#define cWidth FIjpnhlAvPDMZDsv
#define cHeight ldAuOHUfTtATlAGG
#define displayItemCount hxAHpMERyfcrvegx
#define topConsCancel WZejvPZEqajGglvG
#define bottomConsCancel oRaxYdLxyXCszlTJ
#define leadConsCancel JbFqSTCapGywduBW
#define trailConsCancel iJfowAKMVANkTBnJ
#define scrollContentView GAYRRRIUdkjJKkCn
#define topCons fopPniZiyxHdlwuG
#define centerCons PaQnszEjfoovyByu
#define widthCons VTFeDRkiahRXryAj
#define heightCons OTsGxfaaENlnizuo
#define itemBtn AbOPKdGqnayrPYaA
#define btnHeightCons fZqfAvgjmzhAQKqZ
#define btnLeftCons hhEpIyDKZGVEBrbF
#define btnRightCons gpphSCRNTfXIyzWh
#define btnTopCons mCOLKQbmRfcKFRtl
#define currentItemBtn PsoErlQKxUNMHvtF
#define itemBtn2 pgTHauSSXOwcStei
#define btnHeightCons2 kPOFcrOPixcfEzwG
#define btnLeftCons2 LbhSdkBFwMbPJfyy
#define btnRightCons2 QDQoXVgBdKQphsHP
#define btnTopCons2 CXNOsOilkrwTIdAe
#define btnBottomCons GwFeNUPoMclTccXI
#define spinnerScrollViewCancel hzaazGAwVgoEloRy
#define spinnerScrollBtnClick ynbOCjsydEJFKeVx
#define setSelection TxCoJycJYMpfAUyj
#define getAbsoluteFame oLMeSVcLSBRrcusl
#define originX dkQpCHBJviQlGXIx
#define originY gIIafKvKxtEtbCty
#define superView lMYfaVhgSxvBTCIh
#define getOutermostView JkwTGiyziIeenucZ
#define UserInfoViewController FOelnJWuCeUKcvGm
#define userInfoTV gdqLTVlEwCsWOOVk
#define UserInfoTableView hGOtNqqHLJwmbLrQ
#define vcInstance dkrFQqhibtitJzXs
#define imagePicker KdTlnGEnHvnLTrkX
#define UserInfoTableViewCell LODXHobOmSrUbztL
#define userImageView vQRlCDfaytVRkeEV
#define userImageIndicator RajJlzfwJENRJMoR
#define userImageSelectBtn BeRGXHMLEuPZBxLp
#define userNicknameTitleLabel wSBhmESEWgieacMv
#define userNicknameLabel HIyYkiCzyhFrcrSu
#define userNicknameBtn GcLWrHddbpwEfBQz
#define userNicknameTextField hDgyNkyXzMKZmAJR
#define userEmailTitleLabel zGxqORWKLdqxPMPl
#define userEmailLabel KtlCKtvLERagQViH
#define userEmailBtn IhNuEfZQBmuVqIAx
#define userEmailTextField ZXpbSzBVWvHiyDts
#define SystemConfig OKQXPNTmixHEzLrU
#define appCateId LYtBpvChbhEJdvDD
#define appMainColor NxgIkkAximoFMNjk
#define appSubColor ZyjjhGRubFegGGIH
#define appSubTransColor cbdcxKtlMQLFEziT
#define appMaskColor DhrVMDcIvGsSWuys
#define appLightColor jgfQxbKhaxIkPUZi
#define mTitleFont MgkgdtmpMMlhEgJv
#define jpushAppKey tSLgzCuQtBCmqsJG
#define jpushChannel CSREmNRLLUVkeeyG
#define leanCloudAppId FMLTcxDqFlPrjALa
#define leanCloudAppKey gocdEcRFhAIpmxAW
#define sendBirdAppKey ImvqXhdgUXQpKptc
#define appSendBirdAccountChannelUrl xoKYzSmzCwDLxbfN
#define appSendBirdNewPageChannelUrl awVFrDbreEOfMKcP
#define appSendBirdDiscussChannelUrl KrqOAPZRQiDBBKid
#define appSendBirdRepostChannelUrl jDeJymmmfaXRkTVY
#define appSendBirdLikeChannelUrl zstTTasstMIynUsP
#define RepostDiscussViewController hgAbTiiVoJUBRBuj
#define backgroundView xGmRiscFGOCibXGU
#define backgroundImageView aWeVqgIjSnikeIFG
#define repostTV CeBDMbbhTBpPtBvM
#define sendView UvanWjawxWdldZgb
#define sendTextField GzBawfcKsuCGmtVi
#define sendBtn qBtrhNvEQDyzsjiC
#define sendBirdDiscussChannelUrl AAKKgwxDiaRFBfJn
#define sendBirdRepostChannelUrl CDDMFSiUANwSkwjJ
#define discussId zPVsJCXNBpylnquY
#define discussObject dofXVmnEbgJnoCnO
#define resetData pwbSDYMzEEmpQWcV
#define discussObjectTemp faDhNZzponGYABPs
#define repostObj ntWOYHyiinMoZJbm
#define setParameter MhSmtOrQNsrpQmbC
#define sendBirdDiscussChannelUrl BQrLQOjOsQRwisLq
#define sendBirdRepostChannelUrl PDJWQZSEyrjJmLQV
#define discussId BbOisiEsDGuPKwBx
#define userInfo CdKDxrRFrIhuHEaV
#define RepostDiscussTableViewCellM zLMohXzxUMiDuHNT
#define cellBackgroundView GmpFCSGravkBPPPu
#define senderImageView spYZGlFxWuMvZbCb
#define senderNicknameLabel EtOtLxskOWIIpfOo
#define accordingImageView gnkRVSkMyNuDABPW
#define accordingTitleLabel PiSpOTlertIyNikS
#define accordingSubTitleLabel SXeDkJbtnGRKnIDF
#define subjectLabel AEkjNrhEAuXUqbeL
#define contentLabel jSExneVdNHzrsMwn
#define RepostDiscussTableViewCellS hUIPEvMDKPGZgqPT
#define cellBackgroundView BOATYvxyHrMLzCRw
#define senderImageView gXXRnYXadPhxsTpq
#define senderNicknameLabel PFKLVGidNFLFiOmh
#define contentLabel LLpacTuLpetpAxMR
#define dateLabel CgvcBEFOjDKegNjw
#define QueryDiscussViewController YwAznHLpxKyFvuRM
#define backgroundView xndnqQYhoHtUyVdB
#define backgroundImageView ywboFJzzswQoJptT
#define discussTV YRWOXsgCXHtmIfxg
#define sendBirdDiscussChannelUrl dxWQmSgBRdNXITTy
#define sendBirdRepostChannelUrl OxfMFyhfwIiCBLKC
#define sendBirdLikeChannelUrl IyDIdjIgHjFfNviQ
#define userInfo IrlSUVizPcQzIaSe
#define discussArray DMAElYtxOJmRngMN
#define accordingClickCallback JIyPnRZHnpcsiOOa
#define repostClickCallback rqcreaoOJSpBrpGB
#define sendBirdDiscussChannelUrl cioFAgaikyrpnrCk
#define sendBirdRepostChannelUrl wcBOQUUqBaSvlnlO
#define sendBirdLikeChannelUrl VEwujfEyuVPpdLOD
#define accordingCallback PAHInzieexZzAYqe
#define cellBackgroundView BpEKrTybbvdMKhcb
#define senderImageView pjIYEOQfrBwxfHym
#define senderNicknameLabel rfxXPiFKoVyarERy
#define accordingImageView VxeDuHAKmlEiZlLc
#define accordingTitleLabel DFvzoyMsyGxitwrP
#define accordingSubTitleLabel UOAYKjDYgTjEAlkl
#define accordingSelectBtn uhYiUlyqRpGkRnEc
#define subjectLabel fvQEBjGhUkpviFBm
#define contentLabel LKBHygnSiwlIvQVd
#define dateLabel rUeswmgORGKZChMW
#define repostBtn JljxCFEZXevZTRpH
#define likeBtn taYJvGIrUihhnnkd
#define backgroundView LihEGSqtGjRLZzhA
#define backgroundImageView SqJJgZSyRQhRllbH
#define sendDiscussView dpJSnlrlshLyVBNe
#define topBarView BPGyYBxkVNKKqcDa
#define topBarTitleLabel MndExfiGPtmljZXB
#define subjectTitleLabel NewMOjNcRcfmtYHK
#define contentTitleLabel YLPsAUpqraIsXyiv
#define subjectStrokeView OhtYENSJLGbvyHgY
#define subjectTextField BCRJrtWlpYmPugKb
#define contentStrokeView QJipgjxYfZAZIPca
#define contentTextField VOXTyJXFpOVaIqMi
#define cancelBtn HmDWJnfSGAFdYiLB
#define sendBtn DrDZVVwaQMpojEzI
#define sendBirdDiscussChannelUrl kBKkeNdnfIKOtEhO
#define accordingObject ATXUHccByOEhGXVh
#define sendClickCallback MapnBmuKbeYkOhBB
#define cancelClickCallback aleYOXwyaYDbfwQH
#define sendBirdDiscussChannelUrl BHhbFwHnyfwyHzLn
#define accordingObj EHIapPBejKOHjdrJ
#define didSendCallback ndZgZDcsFYhfaKWL
#define discussObj zevlJbMYQNkNfnvI
#define cancelCallback hiWLtDbsRbSEcCze
#define LoginViewController AXcuGmLFjxrGYpbS
#define backgroundView LQzYmBGggeeQXnpo
#define backgroundImageView ftyLGnYChFlFVxOn
#define loginView zNhyTacXXxAfMTuZ
#define topBarView dhrXLZTatXyHqwpY
#define topBarTitleLabel qLEIiBrdTbtiuTOk
#define accountTitleLabel GjkfjXHYLcpQgjKv
#define passwordTitleLabel aABlNwvvMrsGxdGK
#define accountStrokeView xXZDzlwcNnwGDquo
#define accountTextField oVqWVWlcxhHSwiRb
#define passwordStrokeView tpaLsfdIfRtuulxN
#define passwordTextField uewlWuFXZUjzUABT
#define cancelBtn ppagIWUryElcdlyZ
#define confirmBtn ZxBOQBiwICkySegW
#define sendBirdAccountChannelUrl jYOyCjAsKvYUJjyf
#define RegisterViewController igDDvEzMZMNZTcDZ
#define backgroundView YialixVHOeEldIJG
#define backgroundImageView fJftwxbPRLNTRthi
#define registerView RYWdqDqcWDBfoREr
#define topBarView KKivqMzSRWloTbZc
#define topBarTitleLabel rAFHmACmiQjLamxI
#define userImageView sXoILikUsVkpJLkx
#define userImageBtn ernjQXaWPWnNcWcv
#define nicknameTitleLabel mYgXkmJDzurLlIJP
#define emailTitleLabel dUWmxWSLxgBXfdAz
#define passwordTitleLabel kXamuuOAVwuvzACe
#define confirmTitleLabel tOwGgyRpWuvaikRq
#define nicknameStrokeView hgHdeCOXnvcIQbst
#define nicknameTextField BxDONaoUnsNpnidh
#define emailStrokeView hjimVwGBzRuTNbLE
#define emailTextField ydZoAzBkaGTfyfmS
#define passwordStrokeView snYcFieEcGPKDaZn
#define passwordTextField jKHJeOVkgNyCXGXU
#define confirmStrokeView KfbHnTFBRQwqGSUu
#define confirmTextField QKlexnzecYdMEJHD
#define cancelBtn HGHlfaOPKWgAocVJ
#define submitBtn OOkXKwHKlnVrnTqi
#define submitClickCallback DJyemQPSQWyQfPdP
#define cancelClickCallback XjZilrdbAZBcscvp
#define imagePicker gZlpSpsggzjThxQS
#define sendBirdLoginChannelUrl RUHEVvgXeCXQrgEh
#define userImageUrl rZkJisoiaLquPJmA
#define sendBirdLoginChannelUrl rmXtHpXVLUYUYfwN
#define sendBirdAccountChannelUrl qEEOUsIDIbrrRotN
#define confirmClickCallback dcsUkUqPQoovBCkS
#define cancelClickCallback MQhFWGwuaOHpNyNr
#define didRegistedCallback NoNMTamQolxSKAOK
#define OverWebViewController TOIDBoLScJnprJBK
#define titleView NhAnTBIdLxRqroiL
#define titleLabel lsMTvtIXjAdgphQM
#define toolsView qDAaYoFkmezszWUf
#define backBtn CXZjQxPZSoONGcZe
#define forwardBtn YLklCmqERvLWDAyd
#define refreshBtn UtmyPegUZouFJrDm
#define shareBtn BUsQiQNQPxbWsUfH
#define wkWebView YNAnhmQDDJlXzudT
#define exitName qzleDTxCfDPaNBHa
#define backName ywEwvnbpyQogogNy
#define forwardName XqGwlYAYuJKUYQtp
#define refreshName VFHdavLBnjOhJGBn
#define shareName BgMTzWbtXivvtgBL
#define titleBarColor PqlNKnilWjNPDJdy
#define titleTextColor IeYxbBdcASYJXNRs
#define titleTextSize WrkeZHWZzJNmBNLg
#define toolsBarColor SLXIPMVSFzQRGZrT
#define toolsBtnColor awXWpcEsFlVycedl
#define toolsBtnTextEnableColor BWowAHoDPdEeCYWn
#define toolsBtnTextDisableColor YkuCIozWrDWiomjz
#define toolsBtnTextSize GhwTcUqwIAWhDHAY
#define cancelClickCallback jfqAPGSmXUCEoHSH
#define accordingArray fxgwEpCJjbSaYSIF
#define isInnerArray ImYuhcVNShgwtaHH
#define currentUrlIndex jhiTAqcdTHkUBKES
#define mainView zpPmYrVFFwIUbDXW
#define leftView zdbizKCphkknQHKo
#define rightView ntCiRLRLemzpwsJm
#define topView UstpQhEaTIKxyBfd
#define bottmView zMhFAGWXjApKbQuJ
#define gotoUrl JtkPMnXalevLNUSN
#define resetBtnColor SBrZMxfczXwXFrQU
#define loadTitleUrl xwReGHJSLliPELTo
#define setCancelCallback KVGsazxHCYvNbDxB
#define backBtnClick wKCadIpfxoVoLIdP
#define forwardBtnClick qLAqZEaIOqYgzAkN
#define refreshBtnClick qEEjJWesLVRNuKEI
#define shareBtnClick WZtwXRhQFOQaKftN
#define addMessageBtn ksyidVwtYCUbgsvN
#define messageBtn MwZOvYcgHGHAqctK
#define sendDiscussVC MtamIxPGKRMwMQZf
#define KeyboardControlExtension aTkAlzKTyuFHGrfm
#define kvcIsKeyboardShow UuusbykfmhwRwInr
#define kvcKeyboardHeight DujfEftEpmAlVBPb
#define kvcMainViewFrame PuYvMVdKvWsgndfp
#define kvcTargetView UgomdXIcniDIwiLF
#define KeyboardViewController plXkESzIzFFqsAMU
#define mainDisplacement TqtIoRVmnrjInPTr
#define bottomInputViewFrame BYmpcWaeyhPXoFTq
#define bottomSpace mAIsPbKQRThFUNXc
#define bottomInputViewFrame mKHROiqtYwgvdGdI
#define bottomSpace rJhXdAVoTghuXMWh
#define kvcGetViewOfAbsoluteFame rAHUWHjqBzXOhKtR
#define SendBirdNavigationController esfmZdvcLujLzlsQ
#define mTitleAttributes DIZBnydWtRJrlbjY
#define UserInfoObject IPTUXoIOCApyfjxd
#define userPassword JRjvUTeZPtticWwR
#define userNickname altVzEYBmsGVKzyp
#define userEmail rSxLcbfjgIDPWsZP
#define userImageUrl SecsiaGTZXVfiggv
#define AttentionObject AxmElfqzPLYDHsih
#define accordingUrlArray doQPQZYNZqvuLKRp
#define NewPageObject oOUuZSKFAefrILXj
#define menuId OgKGIkSwsFFgvUKy
#define cateName dPHYZOEIQzvKLQrY
#define titleName JAPuDwmttJiGPhlz
#define subTitleName uSgnMPFryFDobOdq
#define tagName OBWkBmzqpuvCRKCS
#define pageUrl ooClKgODePPVttqY
#define imageUrl bBgaqfSvwWGHFMZE
#define editTime zxavnthZCDQVVqqK
#define isAttention wViimCznXonycetJ
#define DiscussObject cmjPgmWSfNawkyCS
#define according AehREhwAuuZVsagI
#define discussId dxXjZEcDyRZSiaRd
#define subject fHcYmYpPtaTOKypw
#define content UYzqDjzcRMODocTc
#define date dbGUSrOAsUClgtKm
#define repostArray ZjGlJQQBSZIchLvI
#define like knBeaWuvqlChskOB
#define DiscussAccordingObject suRHYohxMnsbLLai
#define accordingUrl kZTYQxioJPffXott
#define accordingImageUrl BVfcCmzuIISpAbTH
#define accordingTitle VPPkGcdVSGHWCwRC
#define accordingSubTitle mgivuyWmAFKCDqfe
#define DiscussRepostObject wMjZfLGaJAnSVqTT
#define discussId llLmjmXwMPaBILuk
#define DiscussLikeObject TRoqbdLSmFYItNEK
#define userInfoArray fyKGbANZPTHjlvpI
#define discussId pPWqroTONNHHnqvj
#define sendBirdInit eDvQNkbFfgiDAwjA
#define sendBirdAppId nlSqZsyMYUXLannC
#define sendMessageTo xGQMxrQNJCSLdXWP
#define sendBirdChannelUrl rsLlcvFyKzYdErYe
#define userId SRINqsIOjwQCopdb
#define messageDic vPAWAWaeDAKOleml
#define didSendCallback BLictMVkDskzdFJU
#define getMessagesFrom iSdHhlWRIhWUhbAy
#define sendBirdChannelUrl dkeBPdDgtKKbBERj
#define numbersOfRange rGSPIwlHWnXOvoKN
#define messageArray RVnBjJnNYdoCJsqt
#define pageOfNumbers iFQCgCenrwgQVxEI
#define listQuery sklpmacIQMxYUzSG
#define getMessagesListQueryLoop ccIPRXUKpmJbMknT
#define responseArray onkmPlKHLZTgAGrB
#define userMsg BhMIiNswvlGccGTM
#define msg iiujihyMttcKGbfP
#define msgData EUtTXfYgUSDNziVh
#define getSendBirdUserInfo EOoQegRDjezxzyAf
#define setSendBirdUserInfo ikcugUmozPngXAvI
#define sendAccountTo vbGfBNMnbeLZtQxB
#define sendBirdAccountChannelUrl pfLwMBwzIYvxqjGE
#define getAccountsFrom QfeBttsuuABGOLBX
#define sendDiscussTo TInWOCGPgxOUXQFK
#define sendBirdDiscussChannelUrl CsvYPqmKmSVhtijt
#define discussObject EalSJrngiSyoVZBM
#define didSendCallback JmGkazFleFkpFWTa
#define getDiscussesFrom kMaOTbXbawrAndJC
#define discussArray JJFAkzLWIHpahWXi
#define sendNewPageTo eYFidPrblfVMrARV
#define sendBirdNewPageChannelUrl AXGcpTchYrufYSeM
#define newPageObject cBCrZUoPdyoCXeOx
#define getNewPagesFrom fefKEDUJcAujmjQb
#define newPageArray dTvULZanmwzBmDag
#define prevMessageListQuery gnxhniwrrXvYtilg
#define sendUserAttentionTo kJXBcaTIceFNJtiH
#define sendBirdAttentionChannelUrl IxljWOVFGgkuACzD
#define attentionObject nrtFIplpsprjhmsz
#define getUserAttentionsFrom WbbUTAvcLLURuJHY
#define attentionArray pwcgFPisSkUjUaql
#define sendRepostTo SkiibOownifYccrv
#define sendBirdRepostChannelUrl FudKdWGAuPrAFDxr
#define repostObject uGMJQNQVmmEogXeW
#define getRepostsFrom cJeQPOwfyVBsBzOM
#define repostArray FWjMjPIBSrdovbNW
#define sendLikeTo XCVGWcNvxmrZfwUO
#define sendBirdLikeChannelUrl dKJcnEHOHkTtdKhh
#define likeObject KJpijukhOYdjlKjQ
#define getLikesFrom kPlsqjIRgynTGMgk
#define likeArray cEjSWgzALDCszdSS
#define getOutermostView cdmMssYCgCcNHRYX
#define getViewOfAbsoluteFame CpFYMyxDGWcuQcUe
#define startIndicator lOnvicafcCvAwvEd
#define currentVC iOHlYsuHMvtEGngE
#define onView NxFDaGVtuREHjmFS
#define stopIndicator KjzxXhwYDFCxadKY
#define indicatorView iHSOXiaGBnXFLwnw
#define matchPattern EUecnNYYKVUdrVjd
#define regex YkuYJyZzEmrfXLHC
#define resizeImageLimited fMJSmVzBSqDjloER
#define backToViewController ySvwoCDicZCTmDAV
#define backToVC FnHieFtoBSEecMBA
#define getDeviceTokenFromUserDefaults iVBqDjrcKwQNEbbW
#define saveDeviceTokenToUserDefaults XqxLixuFHmdSDiaF
#define deviceToken dYmSrHqgSGfiVKAI
#define getCoreDataContext GTNTQesHmfwDbvXg
#define entityName TApwJHkkvPTmHjbP
#define persistentContainer CeikHAyfgHcyNfAP
#define coreDataExample dQSNEspjEuXUsNei
#define uploadImageGetLink cwvREYfiUjpstaXS
#define urlString DiXwpILoVqJXjvgt
#define authorization UTWuDLBDrqcQEgRV
#define mashapeKey fqmVWCGcAjnQqAQc
#define resizeImage zJrkXYEYpGtSJaYv
#define imageData YAePqmGAAaZItsJt
#define imageBase64 wYzUUwtoLBMzUmTC
#define parameters zDeQvidZWZnhLQKX
#define getDownArrow EKJcgTFmKkiKScbw
#define isSameUrl lIDXiUJcjOMYvItR
#define MatrixConcatenation SfMTYQlJQOnnUCTe
#define MatrixOrDouble mjlpuoVCsSffnFre
#define horizontalConcatenate YfAjhLrQvoJyFUPM
#define resData aJcOPnQWzEoXNoAN
#define verticalConcatenate mQwcaQHckVxRuoWQ
#define Matrix qdCKFaTLnQOLJApU
#define AAPoint iTzRMgbojGzqFKiG
#define translation ALLWzvwamKcvFUpl
#define MatrixMultiplication NIxJkyTrWYlkTpoQ
#define AASphereView oPfSMtsYnLWZeLyE
#define MatrixCreation oJNEoLZDPBLvZWoB
#define MatrixSubscripting VDgqJbGQqojyYkOd
#define sphereContentView jFvguIoRibUnmkrD
#define sphereView rhfvRUXcjJEgmYVh
#define resetSphereView pcJsFOBuWveikaQD
#define showSphere XFbjpLsUzErSsWJp
#define tags oWWGReZKFLYfTyqM
#define displaySize duLjFLknMYlUXuHo
#define button pwvtRccGXfgJQwXj
#define overWebVC SuwFAQycShZAmFne
#define accObj nQqmUntRfJTHmsvi
#define CurrencyObject CSWuUawdAAzjLYnn
#define id BoYdmWNoYfaIJciQ
#define currencyName WucgaAgtCOqDukTw
#define currencySymbol GGJckRWJBLgMZAhQ
#define CurrencyTools FDXMkNrbNmuazmtS
#define freeCurrencyApiUrl pZjYBUadqZuzxPCN
#define freeCurrencyAppKey zoyVEDsiLJWsYKSy
#define CurrencyName FtMTPckwlPpPycqq
#define en mDvPoDCceoFKjIoa
#define cn PgPffjrsdXnhekFv
#define getCurrencyNameCn IkFeHGUeFrnskzYT
#define getCurrencyObjectArray EisghdVrcEClDsFm
#define currencyArray xZqsbTCVAzqCmXYY
#define currencyDic rjneDoXdpnlaAsld
#define currencyKey NwambjzrOmyOvxyw
#define currencyName WMVOqSGoowxWlwiD
#define currencySymbol jlYSpxdVUptvOvkO
#define currencyObj rKsptwOJoEjbFCde
#define currencyMainView IuYelflowZjwWysH
#define currencyTitleLabel xkQivQVyxikCipKz
#define currencyFromView uwWQvslbxPRXUQzR
#define currencyDescLabel1 YzzfQsffslbEekJv
#define currencyToView mtzFPzTybxZYQXtE
#define currencyDescLabel2 DFeollBmftixQvJB
#define currencyInputTextField KklaZoCtSjKaknIi
#define currencyStartBtn AvvbGKfrDUAgdsEQ
#define currencyResultTitleView SpfnSPtLRsNEwWzV
#define currencyResultTitleLabel JXcTzveptelnShJo
#define currencyResultLabelMain HnjgugrpTHvXWBKs
#define currencyResultLabelSub hdYpPjupqCYlOFwB
#define currencyFromSpinner LYKPvhhFgccdhVcE
#define currencyToSpinner JstURXeeABiyjLJH
#define currencyObjectArray PojOhiuSBlneFfOF
#define currencyNameArray pbKVrcKqJMgfTiUj
#define currencyFromNameArray RCijDkUKHmhkFhGT
#define currencyToNameArray SfeMTiuYLhEcitkY
#define isSpinnerInit HZUDurLvoGEaBqnb
#define currencyObjArray frAoVVUoHkMdKhnn
#define valueText nwmtGTwqlGMFaStG
#define valueDouble nLZZyedFEXRzJbAW
#define fromObjIndex VRGmKLbxxXeNHZcY
#define toObjIndex RpphmBomeNISffCn
#define fromConName zlMNCLkadIsbnQIT
#define toConName fEIgMlTFOxDsVwje
#define currencyPer LLsTkjSJPMfqBXyr
#define per vwGSdYFsPFVjplgJ
#define formatter mKWFHiDCzTzElACB
#define valueString FJNOXVbiUnuYUEye
#endif
